### ISSUE TITLE
插件失效了

### ISSUE THREAD

**Issue by zsgcgrs** [islock/mobilel6#1]
Home Assistant 2023.5.0，最新版插件不能用了，重启两次后情况依旧，请大神有时间修复一下，谢谢！

Unexpected error importing mobileL6/diagnostics.py
18:13:25 – (ERROR) loader.py - 消息首次出现在 18:13:25，显示了 5 次
Config entry 'L6-39B' for mobileL6 integration not ready yet: [Errno -4000] Network timeout: No response received within 10s; Retrying in background
18:13:25 – (WARNING) config_entries.py - 消息首次出现在 18:13:25，显示了 9 次

**Comment by zsgcgrs** [comment]
修改文件 custom_components/mobilel6/device.py，把129行
原self.hass.config_entries.async_setup_platforms(
改为await self.hass.config_entries.async_forward_entry_setups(
亲测有效
来自https://bbs.hassbian.com/thread-18620-26-1.html     253楼，感谢bg6cq大佬

**Comment by islock** [comment]
感谢， 测试 2023.6.2 正常
